name: Merge prices at midnight MYT

on:
  schedule:
    # 00:00 MYT on 6 Aug = 16:00 UTC on 5 Aug
    - cron: '0 16 5 8 *'
  workflow_dispatch: # optional: allow manual test run

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Change 3 to your PR number
          gh pr merge 1 --merge --repo fengshun97/Petrol-Calculator-Prices
